version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description : sales of greenweez
        tests :
          - unique:
              column_name: "(orders_id ||'-'|| pdt_id)"
        loaded_at_field: "CAST (date_date as timestamp)"
        freshness:
          warn_after: {count: 90, period: day}
        columns : 
          - name : date_date
            description : date of purchase
          - name : orders_id
            description : id de l'order                  
          - name : pdt_id
            description : id du produit
          - name : revenue
            description : le revenue
          - name : quantity
            description : c'est la quantite

      - name: product
        identifier: raw_gz_product
        description : products od greenweez
        columns : 
          - name : products_id
            description : les produits
            tests : 
              - unique
              - not_null
          - name : purchase_price
            description : le prix d'achat
      - name: ship
        identifier: raw_gz_ship
        description : le transfert de marchandises
        columns : 
          - name : orders_id
            description : l'id des orders
            tests : 
              - unique
              - not_null
          - name : shipping_fee 
            description : les frais d'envoi
          - name : logCost
            description : les frais de logistique
          - name : ship_cost
            description : le ship cost

      - name: adwords
        identifier: raw_gz_adwords
        description : données de adwords
        tests :
          - unique:
              column_name: "(date_date ||'-'|| campaign_key)"
        columns : 
          - name : date_date
            description : la date
          - name : paid_source
            description : la source de paiement
          - name : campaign_key
            description : la clé de campagne
          - name : campgn_name
            description : le nom de la campagne
          - name : ads_cost
            description : les coûts ads
          - name : impression
            description : lenombre d'impression
          - name : click
            description : le nombre de clicks
      - name: bing
        identifier: raw_gz_bing
        description : données de bing
        tests :
          - unique:
              column_name: "(date_date ||'-'|| campaign_key)"
        columns : 
          - name : date_date
            description : la date
          - name : paid_source
            description : la source de paiement
          - name : campaign_key
            description : la clé de campagne
          - name : campgn_name
            description : le nom de la campagne
          - name : ads_cost
            description : les coûts ads
          - name : impression
            description : lenombre d'impression
          - name : click
            description : le nombre de clicks
      - name: criteo
        identifier: raw_gz_criteo
        description : données de criteo
        tests :
          - unique:
              column_name: "(date_date ||'-'|| campaign_key)"
        columns : 
          - name : date_date
            description : la date
          - name : paid_source
            description : la source de paiement
          - name : campaign_key
            description : la clé de campagne
          - name : campgn_name
            description : le nom de la campagne
          - name : ads_cost
            description : les coûts ads
          - name : impression
            description : lenombre d'impression
          - name : click
            description : le nombre de clicks
      - name: facebook
        identifier: raw_gz_facebook
        description : données de facebook
        tests :
          - unique:
              column_name: "(date_date ||'-'|| campaign_key)"
        columns : 
          - name : date_date
            description : la date
          - name : paid_source
            description : la source de paiement
          - name : campaign_key
            description : la clé de campagne
          - name : campgn_name
            description : le nom de la campagne
          - name : ads_cost
            description : les coûts ads
          - name : impression
            description : lenombre d'impression
          - name : click
            description : le nombre de clicks

models:
  - name: int_campaigns_day
    description: données de campagnes par jour
    columns: 
      - name: date_date
        description : date 
        tests: 
          - not_null
      - name: ads_cost
        description : ads cost par jour
      - name: ads_impression
        description : ads impression par jour
      - name: ads_clicks
        description : ads clicks par jour
  - name: finance_campaigns_day
    description: données de campagnes et finances par jour
    columns: 
      - name: date_date
        description : date
        tests: 
          - not_null
      - name: ads_margin
        description : marge sur la publicité
      - name: average_basket
        description : panier moyen
      - name: operational_margin
        description : marge opérationnelle
      - name: ads_cost
        description : coût de publicité
      - name: ads_impression
        description : nombre d'impression
      - name: ads_click
        description : nombre de clicks
      - name: quantity
        description : quantité
      - name: revenue
        description : chiffre d'affaire
      - name: purchase_cost
        description : coût de l'achat
      - name: margin
        description : marge
      - name: shipping_fee
        description : frais d'envoi
      - name: logcost
        description : coût de logistique
      - name: ship_cost
        description : coût de transport
